# Generated by Django 4.2 on 2023-04-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd_app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
