# Generated by Django 4.2.1 on 2023-05-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jd_app', '0004_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
